# Generated by Django 2.0.3 on 2018-04-05 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Type a comment', max_length=255)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='canvas',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='canvastag',
            options={'ordering': ('label',)},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='ideacategory',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='canvas',
            old_name='public',
            new_name='is_public',
        ),
        migrations.RemoveField(
            model_name='canvastag',
            name='text',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='canvas_tags',
        ),
        migrations.AddField(
            model_name='canvas',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='catalog.CanvasTag'),
        ),
        migrations.AddField(
            model_name='canvastag',
            name='label',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideacategory',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canvas',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='idea',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Canvas'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='text',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.Idea'),
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
