# Generated by Django 2.0.3 on 2018-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180424_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
