# Generated by Django 2.0.3 on 2018-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180424_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
