# Generated by Django 2.0.3 on 2018-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180426_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideacomment',
            name='author_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
