# Generated by Django 2.0.3 on 2018-04-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_ideacomment_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideacomment',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='canvastag',
            name='label',
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
