# Generated by Django 2.0.3 on 2018-05-01 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180430_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvastag',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AddField(
            model_name='canvastag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canvastag',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
