# Generated by Django 2.0.3 on 2018-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180501_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='canvas_set', to='catalog.CanvasTag'),
        ),
        migrations.AlterField(
            model_name='canvastag',
            name='label',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.PositiveSmallIntegerField(db_index=True, default=9),
        ),
    ]
