# Generated by Django 2.0.3 on 2018-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180515_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacomment',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
