# Generated by Django 2.0.5 on 2018-06-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180517_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='is_ethics',
            field=models.BooleanField(default=True),
        ),
    ]
