# Generated by Django 2.0.5 on 2018-06-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_canvas_is_ethics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='is_temporary',
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='users',
        ),
        migrations.AlterField(
            model_name='canvas',
            name='title',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AddField(
            model_name='canvas',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='catalog.Project'),
        ),
    ]
