# Generated by Django 2.0.5 on 2018-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180618_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='is_ethics',
        ),
        migrations.AddField(
            model_name='canvas',
            name='canvas_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
