# Generated by Django 2.0.5 on 2018-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180622_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvastag',
            name='idea',
            field=models.ManyToManyField(blank=True, related_name='tag_set', to='catalog.Idea'),
        ),
    ]
