# Generated by Django 2.0.5 on 2018-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180702_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvastag',
            name='idea',
            field=models.ManyToManyField(db_index=True, related_name='tag_set', to='catalog.Idea'),
        ),
    ]
