# Generated by Django 2.0.5 on 2018-07-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180702_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvastag',
            old_name='idea',
            new_name='ideas',
        ),
    ]
