# Generated by Django 2.0.5 on 2018-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20180702_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvastag',
            name='ideas',
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='idea_set', to='catalog.CanvasTag'),
        ),
    ]
