# Generated by Django 2.0.5 on 2018-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20180702_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideacomment',
            name='tags',
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='idea_set', to='catalog.CanvasTag'),
        ),
    ]
