# Generated by Django 2.0.5 on 2018-07-10 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20180710_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(null=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(null=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
